### ISSUE TITLE
Not work on eGalaxTouch driver

### ISSUE THREAD

**Issue by mgrsantox** [Aadesh-Baral/disable-touch#1]
**It doesn't work on my computer**

- OS: Ubuntu 20.04
- Touch Screen drive: eGalax Inc. eGalaxTouch

**Comment by Aadesh-Baral** [comment]
FIxed by https://github.com/Aadesh-Baral/disable-touch/commit/0284b4cf896690ba9897a473d2f593c5bdc1de48
